pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
        stage("SCM checkout") {
            steps{
                script {
                    sh 'https://github.com/gauri17-pro/terraform-jenkins-eks.git'
                }
            }

        }

        stage("terraform initialization") {
            steps{
                script {
                    dir('EKS'){
                    sh 'terraform init' }
                }
            }

        }
        stage("terraform plan") {
            steps{
                script {
                    dir('EKS'){
                          sh 'terraform plan' }
                }
            }

        }
        stage("terraform autoapprove") {
            steps{
                script {
                    dir('EKS'){
                       sh 'terraform apply --auto-appprove'
                    }
                    
                }
            }

        }
    }
}